### PR TITLE
Added commands to makefile for Install & Uninstall

### PR DESCRIPTION
**Pull request by Wingie**
`make install` will install libraries in `/usr/share/ngs/`
`make uninstall` will delete contents of the above folder

### CODE REVIEW

**Comment by ilyash** [comment]
Thanks!

Could you please adjust the commands as per https://www.gnu.org/prep/standards/html_node/Directory-Variables.html ? default `prefix` would be `/usr` and so on. Note no trailing slash, please add it in the `cp` commands.

Optional / later: It would be also nice to add a test .travis.yml that would make sure the installation went OK... and removal.

**Comment by Wingie** [comment]
Interesting read that was.
if i put the files in `/usr/local/share/ngs/` the binary no longer finds it when invoked with `./ngs demo/ec2din.ngs`

**Comment by ilyash** [comment]
Yep. I've edited my comment above so you probably missed it: you should also modify `ngs.c` to look at the location specified at build time.

**Comment by ilyash** [comment]
Merged with modifications. Needs testing but I can't do it right now.

**Comment by ilyash** [comment]
Thanks!

**Pull request merged**
